### ISSUE TITLE
Implementation of fold

### ISSUE THREAD

**Issue by wahani** [zatonovo/lambda.tools#9]
I was just reading the fabulous chapter 4 of *Modelling Data With FP in R*. I have two concerns with the specific implementation of `fold` presented in the chapter and implemented in `lambda.tools`. One is the memory usage of the implementation which can easily exceed the available amount as illustrated by the following example. This is becaue `sapply` will keep the result of each iteration, although this is unnecessary. Returning `NULL` explicitly in the anonymous function will fix this:

```R
lambda.tools::fold(1:1e5, c, 0) # does not complete on my maschine

fold <- function(x, fun, acc) {
  lapply(x, function(xi) {
    acc <<- fun(xi, acc)
    NULL
    })
  acc
}

fold(1:1e5, c, 0) # does complete

```

Also I see no need to use `sapply` since it is a wrapper around `lapply` and the additional simplification of the return value is not needed for fold. 

The second problem I see - I have no solution - is that in the scenario where the return value of fold has length `n` or `n + 1` where `n` is the length of `x`, replacing the value of `acc` in each repetition can be very inefficient - or more general in a scenario where the memory size of `acc` increases in each iteration. I would consider folding a list of data frames as a usecase of fold where this becomes critical:

```R
dataFrame <- fold(listOfDataFrames, rbind, NULL)
```

There are of course very specific solutions for the above task, but given the generic vocable of fold I think it should be considered.

-s

**Comment by muxspace** [comment]
Hi thanks for your kind words and documenting your concerns regarding my `fold` implementation. That's a good idea regarding adding `NULL` as a return value. If you submit a pull request, I'll merge it in. In terms of `sapply` vs `lapply` as the underlying mechanism, I use the simplified values quite often, which is useful not only when you return vectors but also matrices.

In terms of the second issue, it would be useful to conduct some benchmarks to see how much impact this has. I would also be interested in seeing how it compares with an equiavalent `Reduce` call.

**Comment by wahani** [comment]
Okay, I played around and can illustrate my concerns. Still, I cannot see a generic solution to the problem. Maybe rewriting fold as a recursive function would be an option but in R this - as far as I know - is not implemented efficiently and not an option... Anyway, [here are the results of the benchmark](http://rpubs.com/wahani/fold-benchmark). `fold` and `Reduce` have the same problem, however `Reduce` has the argument accumulate, which can be helpful in some cases, but not in my example... 

The code without results:

```R
library("microbenchmark")

fold <- function(x, fun, acc) {
  sapply(x, function(xi) {
    acc <<- fun(xi, acc)
    NULL
  })
  acc
}

foldLapply <- function(x, fun, acc) {
  lapply(x, function(xi) {
    acc <<- fun(xi, acc)
    NULL
  })
  acc
}

microbenchmark(
  fold(1:1e3, `+`, 0),
  foldLapply(1:1e3, `+`, 0)
)

df <- data.frame(x = rnorm(400^2), group = as.character(1:400))
listOfDataFrames <- split(df, df$group)

system.time(lambda.tools::fold(listOfDataFrames, rbind, NULL))
system.time(fold(listOfDataFrames, rbind, NULL))
system.time(foldLapply(listOfDataFrames, rbind, NULL))
system.time(Reduce(rbind, listOfDataFrames, NULL))
system.time(do.call(rbind, listOfDataFrames))
system.time(dplyr::rbind_all(listOfDataFrames))

# In the end the fold/Reduce implementations have the same problem as:

system.time({
  ret <- 0
  for (i in 1:1e5) {
    ret <- c(i, ret)
  }
})

# Which could be overcome defining the length of the output
# in advance ...

system.time({
  n <- 1e5
  ret <- numeric(n)
  for (i in 1:n) {
    ret[i] <- i
  }
})
```

**Comment by muxspace** [comment]
So using `sapply(..., simplify=FALSE)` results in basically the same performance as `lapply`, which is expected. For me I prefer the optionality of having the result simplified, and if not just passing `simplify=FALSE` to `fold`.
```R
> microbenchmark(
+   fold(1:1e3, `+`, 0),
+   foldLapply(1:1e3, `+`, 0)
+ )
Unit: milliseconds
                       expr      min       lq     mean   median       uq
       fold(1:1000, `+`, 0) 1.421777 1.458597 1.583353 1.475105 1.539400
 foldLapply(1:1000, `+`, 0) 1.399531 1.440542 1.574544 1.462093 1.506344
      max neval
 3.098052   100
 3.090126   100
```

In terms of the other benchmark, using `do.call(rbind, ...)` will obviously perform best (as you noted). I imagine there are optimizations that can be made for specific cases, although my current focus is pedagogy and not maximal performance. Eventually, it would make sense to implement it in C, at which point the performance would be markedly faster.
